# Permalinks
permalink:           none

# Setup
title:               How To Make A Hit Movie
tagline:             Project for ADA 2018
#url:                 ""
baseurl:             ""
analytics_id:

# Owner/author information
owner:
  name:           ZHOU Xiao & LIU Jiafan


# Custom vars
version:             1
github:
  repo:              

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
plugins:
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM 
